version: '3.8'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: O16s12@96
    ports:
      - "3307:3306"
    volumes: 
      - db-data:/var/lib/mysql
    networks: 
      - music_app_network
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile
    environment: 
      DB_USERNAME: root
      DB_PASSWORD: O16s12@96
      DEV_DB_DATABASE: music_app_dev
      DB_HOST: localhost
      JWT_SECRET: JWT_SECRET
      ELS_URL: http://elasticsearch:9200
      PORT: 8080
    command: ["./wait-for-it.sh", "mysql:3306", "--", "npm", "run", "all:dev"]
    ports: 
      - "8080:8080"  
    networks: 
      - music_app_network
      # - elastic
  # elastic_search:
  #   container_name: music_elastic_search
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
  #   environment:
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - discovery.type=single-node
  #   logging: 
  #       driver: none
  #   volumes:
  #     - search:/usr/share/elasticsearch/data
  #   ports:
  #     - 9300:9300
  #     - 9200:9200
  #   networks:
  #     - elastic
  
  # client: 
  #   build: 
  #     context: ./client
  #     dockerfile: Dockerfile
  #   ports: 
  #     - "3000:3000"  
  #   networks: 
  #     - music_app_network
networks:
  music_app_network:
  elastic:
    driver: bridge
volumes:
  db-data: 
  search:
    driver: local
  


